services:
  outline:
    image: outlinewiki/outline
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - outline-data:/var/lib/outline/data

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "$PGPORT:$PGPORT"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - outline

volumes:
  outline-data:
  pgdata:
  redisdata:
