services:
  outline:
    image: outlinewiki/outline
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - outline-data:/var/lib/outline/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.outline-wiki.entrypoints: "websecure"
      traefik.http.routers.outline-wiki.rule: "Host(`${FQDN}`)"
      traefik.http.services.outline-wiki.loadbalancer.server.port: 3000
      traefik.http.routers.outline-wiki.tls: "true"
      traefik.http.routers.outline-wiki.tls.certresolver: "letsencrypt"
    networks:
      - proxy
      - default

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "$PGPORT:$PGPORT"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

volumes:
  outline-data:
  pgdata:
  redisdata:

networks:
  proxy:
    external: true
